import Link from "next/link";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

const businessTypes = ["General business", "Hotel and hospitality", "Healthcare", "Professional services", "Marketing agency", "E-commerce", "Education", "Logistics", "Other"];
const goals = ["Customer support", "Sales follow-up", "Content creation", "Reports", "Lead management", "Task automation", "Document processing", "Notifications"];
const templates = ["New lead assistant", "Weekly business report", "Customer support triage", "Social content approval"];

export default function Page() {
  return <main className="min-h-screen bg-background p-4 md:p-8"><div className="mx-auto max-w-5xl space-y-5"><header className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h1 className="text-2xl font-semibold">Set up FlowPilot AI</h1><p className="mt-1 text-sm text-muted-foreground">Create a useful workspace state in a few guided steps. Optional steps can be skipped and resumed later.</p></div><Button asChild><Link href="/app/dashboard">Skip to dashboard <ArrowRight className="size-4" /></Link></Button></header><div className="h-2 rounded-full bg-muted"><div className="h-2 w-5/8 rounded-full bg-primary" /></div><div className="grid gap-4 lg:grid-cols-[1fr_320px]"><Card><CardHeader><CardTitle>Workspace and goals</CardTitle></CardHeader><CardContent className="space-y-5"><div className="grid gap-3 md:grid-cols-2"><Input defaultValue="Acme Operations" /><Input defaultValue="Africa/Nairobi" /></div><section><h2 className="mb-2 text-sm font-semibold">Business type</h2><div className="grid gap-2 md:grid-cols-3">{businessTypes.map((type) => <button key={type} className="rounded-md border p-3 text-left text-sm hover:bg-muted">{type}</button>)}</div></section><section><h2 className="mb-2 text-sm font-semibold">Automation goals</h2><div className="grid gap-2 md:grid-cols-4">{goals.map((goal) => <label key={goal} className="flex items-center gap-2 rounded-md border p-3 text-sm"><input type="checkbox" defaultChecked={["Sales follow-up", "Reports", "Task automation"].includes(goal)} />{goal}</label>)}</div></section><section><h2 className="mb-2 text-sm font-semibold">Recommended templates</h2><div className="grid gap-2 md:grid-cols-2">{templates.map((template) => <div key={template} className="rounded-md border p-3 text-sm"><div className="font-medium">{template}</div><div className="text-xs text-muted-foreground">Creates a valid workflow foundation from seed/demo actions.</div></div>)}</div></section></CardContent></Card><Card><CardHeader><CardTitle>Setup checklist</CardTitle></CardHeader><CardContent className="space-y-3 text-sm">{["Workspace confirmed", "Business type selected", "Goals selected", "Templates recommended", "First AI agent ready", "First workflow ready", "Invite teammates", "Complete setup"].map((item, index) => <div key={item} className="flex items-center gap-2"><CheckCircle2 className={index < 6 ? "size-4 text-emerald-600" : "size-4 text-muted-foreground"} />{item}</div>)}<Button className="mt-3 w-full" asChild><Link href="/app/dashboard">Complete setup</Link></Button></CardContent></Card></div></div></main>;
}