import { Bot, CheckCircle2, FlaskConical, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { PageFrame } from "@/components/page-frame";

const templates = ["Customer Support Agent", "Sales Follow-up Agent", "Social Content Agent", "Business Reporting Agent", "Document Processing Agent", "Operations Assistant"];
const tools = ["workspace.get_context", "contacts.create", "tasks.create", "notifications.create", "reports.generate", "http.request"];

export default function Page() {
  return <PageFrame title="Create agent" description="A guided Agent Studio form for identity, instructions, model routing, tools, approvals, and local mock testing." actions={<Button><Bot className="size-4" />Save draft</Button>}>
    <div className="grid gap-4 xl:grid-cols-[1fr_360px]"><div className="space-y-4"><Card><CardHeader><CardTitle>Identity</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Input placeholder="Agent name" /><Input placeholder="Purpose" /><textarea className="min-h-24 rounded-md border bg-background p-3 text-sm md:col-span-2" placeholder="Description and business context" />{templates.map((template) => <button key={template} className="rounded-md border p-3 text-left text-sm hover:bg-muted">{template}</button>)}</CardContent></Card><Card><CardHeader><CardTitle>Instructions</CardTitle></CardHeader><CardContent className="space-y-3"><textarea className="min-h-40 w-full rounded-md border bg-background p-3 text-sm" defaultValue="Use only approved tools. Return structured output. Ask for approval before sensitive actions." /><div className="grid gap-3 md:grid-cols-3"><Input placeholder="Goal" /><Input placeholder="Restriction" /><Input placeholder="Output schema" /></div></CardContent></Card><Card><CardHeader><CardTitle>Model and runtime</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-3"><Input defaultValue="mock" /><Input defaultValue="mock-business-agent" /><Input defaultValue="0.2" /><Input defaultValue="6 max steps" /><Input defaultValue="60s timeout" /><Input defaultValue="structured output" /></CardContent></Card></div><aside className="space-y-4"><Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-4 text-primary" />Tools and approval</CardTitle></CardHeader><CardContent className="space-y-2">{tools.map((tool) => <label key={tool} className="flex items-center justify-between rounded-md border p-2 text-sm"><span>{tool}</span><input type="checkbox" defaultChecked={!tool.includes("http")} /></label>)}<div className="rounded-md bg-muted p-3 text-sm">Approval policy: write and destructive actions pause for review.</div></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><FlaskConical className="size-4 text-primary" />Test run</CardTitle></CardHeader><CardContent className="space-y-3"><textarea className="min-h-24 w-full rounded-md border bg-background p-3 text-sm" defaultValue="Classify this hotel follow-up lead and create a task." /><Button variant="outline" className="w-full"><CheckCircle2 className="size-4" />Run with mock provider</Button><pre className="overflow-auto rounded-md bg-muted p-3 text-xs"><code>{JSON.stringify({ status: "ready", provider: "mock", validation: "zod schema enforced" }, null, 2)}</code></pre></CardContent></Card></aside></div>
  </PageFrame>;
}